// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Jump
{
    internal sealed partial class Vsix
    {
        public const string Id = "Jump.92c92e50-2115-49f9-afdd-8c6f0370c521";
        public const string Name = "Jump";
        public const string Description = @"Jump to files in entire solution to specifice line.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "David Kuzanashvili";
        public const string Tags = "";
    }
}
