// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Jump
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string JumpString = "8b0c3eb6-36cc-4c45-bcfd-7e171e1c13cb";
        public static Guid Jump = new Guid(JumpString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int JumpMenuGroup = 0x0001;
        public const int OpenDialogCommand = 0x0100;
    }
}